name: daily-rebooter
title: Daily rebooter
version: '10'
base: core24
summary: Reboot every day at a given time
contact: sportogo@miezal.net
source-code: https://github.com/meo2k1/daily-rebooter-snap
website: https://github.com/meo2k1/daily-rebooter-snap
license: MIT
description: |
     This is a fork of https://github.com/mauringo/midenight-rebooter-snap/tree/main/shscripts
     It can reboot at any time requested by snap set time="hh:mm". 
      
confinement: strict
grade: stable

    
apps:
  rebooter: 
    command: bin/runserver.sh  
    plugs:
      - network-control
      - network-observe
      - network
      - shutdown
    daemon: simple 

parts:
  flask:
    plugin: python
    python-packages: [schedule]
    source: ./src
    build-packages:
      - python3-dev
      - build-essential

  python-code:  
    source: ./src/
    plugin: dump
    organize:
      '*': bin/Flask/

  scripts:  
    source: ./scripts/
    plugin: dump
    organize:
      '*': bin/


